### ISSUE TITLE
How do I install spirit-linux?

### ISSUE THREAD

**Issue by zdavatz** [posixninja/spirit-linux#6] opened 2010-05-31 03:55 UTC
I done "make" and I get:

spirit.c:379: warning: implicit declaration of function 'idevice_get_device_list'
spirit.c:386: warning: implicit declaration of function 'idevice_device_list_free'
spirit.c:389: error: 'device_error' undeclared (first use in this function)
spirit.c:389: warning: implicit declaration of function 'idevice_new'
spirit.c:389: error: 'device' undeclared (first use in this function)
spirit.c:390: error: 'IDEVICE_E_SUCCESS' undeclared (first use in this function)
spirit.c:391: error: 'IDEVICE_E_NO_DEVICE' undeclared (first use in this function)
spirit.c:404: warning: implicit declaration of function 'idevice_free'
make: **\* [spirit.o] Error 1

at the end. Any hints?

Best
Zeno

**Comment by zdavatz** [comment] 2010-05-31 04:16
Ok, stupid question of mine, sorry. I am emerging libimobiledevice-1.0.1 and will report back later.

**Comment by posixninja** [comment] 2010-06-08 23:50
sounds like the problem is solved so i'm closing this issue

**Comment by zdavatz** [comment] 2010-06-09 03:29
yes, works fine now!

**Closed as completed** 2010-06-09 06:50 UTC
